"""
Answer Agent Node

For each question generated by the Question Agent, produces:
- 1 correct answer (verified against analysis data)
- 3 plausible distractors
"""

import json
import logging
import time
from typing import Optional

from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage

from question_engine.state import QLCState

logger = logging.getLogger(__name__)

ANSWER_SYSTEM_PROMPT = """You are an expert at crafting multiple-choice answers for programming
comprehension questions.

For each question you receive, you must produce:
1. ONE correct answer — verified against the analysis data
2. THREE distractor answers — plausible but wrong

Guidelines for distractors:
- Each distractor must be a COMMON MISCONCEPTION or PLAUSIBLE MISTAKE
- Distractors should be the same "shape" as the correct answer (same type,
  similar length for text, same scale for numbers)
- Off-by-one errors, wrong variable references, and type confusion are excellent distractors
- Never make a distractor obviously wrong (e.g., "banana" for a numeric question)

For each distractor, note what misconception it targets in the "misconception_targeted" field.

Return ONLY valid JSON in the format:
{
  "answers": [
    {
      "question_index": 0,
      "correct_answer": {
        "text": "<answer>",
        "verified": true,
        "verification_method": "dynamic_analysis | static_analysis | reasoning"
      },
      "distractors": [
        {"text": "<distractor>", "misconception_targeted": "<description>"},
        {"text": "<distractor>", "misconception_targeted": "<description>"},
        {"text": "<distractor>", "misconception_targeted": "<description>"}
      ]
    }
  ]
}"""


def _compact_analysis(static: Optional[dict], dynamic: Optional[dict]) -> str:
    """Return a compact analysis representation for the answer prompt."""
    out: dict = {}
    if static:
        out["static"] = {
            "summary": static.get("summary", {}),
            "functions": [
                {k: v for k, v in fn.items() if k in
                 ("name", "params", "is_recursive", "return_type", "line_start")}
                for fn in static.get("functions", [])[:10]
            ],
            "variables": [
                {k: v for k, v in vr.items() if k in ("name", "scope", "inferred_type")}
                for vr in static.get("variables", [])[:15]
            ],
            "loops": static.get("loops", [])[:10],
        }
    if dynamic:
        out["dynamic"] = {
            "execution_successful": dynamic.get("execution_successful"),
            "final_variables": dict(list(dynamic.get("final_variables", {}).items())[:15]),
            "function_calls": dynamic.get("function_calls", [])[:10],
            "loop_executions": dynamic.get("loop_executions", {}),
            "stdout": (dynamic.get("stdout") or "")[:500],
        }
    return json.dumps(out, default=str)


def answer_agent_node(state: QLCState) -> dict:
    """
    LangGraph node: Generate correct answers and distractors for each question.

    Updates state with:
    - questions_with_answers: list of enriched question dicts
    - tokens_used (incremented)
    """
    start = time.time()
    config: dict = state.get("config", {})
    model: str = config.get("answer_model", "gpt-4o")
    source_code: str = state["source_code"]
    questions: list[dict] = state.get("questions", [])
    static_analysis: Optional[dict] = state.get("static_analysis")
    dynamic_analysis: Optional[dict] = state.get("dynamic_analysis")

    tokens_used = state.get("tokens_used", 0)

    if not questions:
        logger.warning("Answer agent received no questions to process")
        return {
            "questions_with_answers": [],
            "tokens_used": tokens_used,
        }

    analysis_text = _compact_analysis(static_analysis, dynamic_analysis)

    questions_json = json.dumps(
        [{"index": i, **q} for i, q in enumerate(questions)],
        indent=2
    )

    user_content = f"""For each of the following questions about this Python code, produce a correct answer
and 3 plausible distractors.

## Student's Code
```python
{source_code}
```

## Analysis Data
```json
{analysis_text}
```

## Questions to Answer
```json
{questions_json}
```

Use the analysis data to verify your correct answers. Return JSON only."""

    llm = ChatOpenAI(model=model, temperature=0.5)
    answers_by_index: dict = {}

    try:
        response = llm.invoke([
            SystemMessage(content=ANSWER_SYSTEM_PROMPT),
            HumanMessage(content=user_content),
        ])

        if hasattr(response, "usage_metadata") and response.usage_metadata:
            tokens_used += response.usage_metadata.get("total_tokens", 0)

        raw = response.content.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        parsed = json.loads(raw)
        for answer_item in parsed.get("answers", []):
            idx = answer_item.get("question_index", -1)
            if idx >= 0:
                answers_by_index[idx] = answer_item

        logger.info("Answer agent processed %d answers", len(answers_by_index))

    except json.JSONDecodeError as e:
        logger.error("Answer agent JSON parse error: %s", e)
    except Exception as e:
        logger.error("Answer agent error: %s", e)

    # Merge answers back into questions
    questions_with_answers = []
    for i, question in enumerate(questions):
        merged = dict(question)
        answer_data = answers_by_index.get(i, {})

        correct = answer_data.get("correct_answer", {})
        distractors = answer_data.get("distractors", [])

        merged["correct_answer"] = correct.get("text", "") if correct else ""
        merged["verification_method"] = correct.get("verification_method", "reasoning") if correct else "reasoning"

        # Build answer_choices list: correct first, then distractors
        choices = []
        if correct:
            choices.append({
                "text": correct.get("text", ""),
                "is_correct": True,
                "misconception_targeted": None,
            })
        for d in distractors[:3]:
            choices.append({
                "text": d.get("text", ""),
                "is_correct": False,
                "misconception_targeted": d.get("misconception_targeted", ""),
            })

        merged["answer_choices"] = choices
        questions_with_answers.append(merged)

    elapsed = (time.time() - start) * 1000
    return {
        "questions_with_answers": questions_with_answers,
        "tokens_used": tokens_used,
        "execution_time_ms": state.get("execution_time_ms", 0.0) + elapsed,
    }
